### ISSUE TITLE
Compatibilidade do collective.cover 1.0a6 com o brasil.gov.paginadestaque 1.0

### ISSUE THREAD

**Issue by luamleiverton** [plonegovbr/brasil.gov.paginadestaque#7]
Prezados.. Na tentativa de realizar a inclusão do produto página destaque, me deparei com problemas de integração destas duas versões de produto, cover e página destaque. Há alguma possibilidade de verificarem e implementarem alguma atualização, de modo a viabilizar a integração, ou ainda sugerir outras estratégias de instalação..

Desde já agradeço

Att

Luam Leiverton
Analista de TI
Univasf

**Comment by idgserpro** [comment]
Qual a versão do IDG você está utilizando?

**Comment by idgserpro** [comment]
Favor adicionar o traceback.

**Comment by luamleiverton** [comment]
Prezado.. segue abaixo..

2016-02-16 14:53:08 INFO ZServer HTTP server started at Tue Feb 16 14:53:08 2016
        Hostname: 0.0.0.0
        Port: 8080
2016-02-16 14:53:08 INFO Zope Set effective user to "plone_daemon"
2016-02-16 14:53:10 INFO Products.PloneFormGen gpg_subprocess initialized, using /usr/bin/gpg
2016-02-16 14:53:10 INFO Products.PloneHotfix20151208 Applied searchFulltextForMembers patch
2016-02-16 14:53:10 INFO Products.PloneHotfix20151208 Hotfix installed
2016-02-16 14:53:10 INFO ZEO.ClientStorage zeostorage ClientStorage (pid=5845) created RW/normal for storage: '1'
2016-02-16 14:53:10 INFO ZEO.cache created temporary cache file '<fdopen>'
2016-02-16 14:53:10 INFO ZEO.zrpc.Connection(C) (127.0.0.1:8100) received handshake 'Z3101'
2016-02-16 14:53:10 INFO ZEO.ClientStorage zeostorage Testing connection <ManagedClientConnection ('127.0.0.1', 8100)>
2016-02-16 14:53:10 INFO ZEO.ClientStorage zeostorage Server authentication protocol None
2016-02-16 14:53:10 INFO ZEO.ClientStorage zeostorage Connected to storage: ('localhost', 8100)
2016-02-16 14:53:10 INFO ZEO.ClientStorage zeostorage No verification necessary -- empty cache
2016-02-16 14:53:11 INFO brasil.gov.portal Patched ResolveUIDAndCaptionFilter
2016-02-16 14:53:11 INFO brasil.gov.portal Patched Link content type
2016-02-16 14:53:11 INFO brasil.gov.portal Patched Related Items widget
2016-02-16 14:53:11 INFO brasil.gov.tiles Patched PersistentCoverTile cover class
2016-02-16 14:53:16 INFO rdflib RDFLib Version: 4.1.2
2016-02-16 14:53:19 INFO ZEO.ClientStorage zeostorage Disconnected from storage: "('localhost', 8100)"
Traceback (most recent call last):
  File "/home/sti-dev/plone4/zeocluster/parts/client1/bin/interpreter", line 363, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 646, in file
    include(context, name, package)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 620, in end
    self.stack.pop().finish()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 774, in finish
    actions = self.handler(context, **args)
  File "/home/sti-dev/plone4/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 620, in end
    self.stack.pop().finish()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 774, in finish
    actions = self.handler(context, **args)
  File "/home/sti-dev/plone4/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/home/sti-dev/plone4/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 620, in end
    self.stack.pop().finish()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 774, in finish
    actions = self.handler(context, **args)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 620, in end
    self.stack.pop().finish()
  File "/home/sti-dev/plone4/buildout-cache/eggs/zope.configuration-3.8.0-py2.7.egg/zope/configuration/config.py", line 774, in finish
    actions = self.handler(context, **args)
  File "/home/sti-dev/plone4/buildout-cache/eggs/grokcore.component-2.5-py2.7.egg/grokcore/component/zcml.py", line 57, in grokDirective
    do_grok(package.__name__, _context, extra_exclude=exclude)
  File "/home/sti-dev/plone4/buildout-cache/eggs/grokcore.component-2.5-py2.7.egg/grokcore/component/zcml.py", line 71, in do_grok
    config=config)
  File "/home/sti-dev/plone4/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 203, in grok_dotted_name
    grok_package(module_info, grokker, **kw)
  File "/home/sti-dev/plone4/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 208, in grok_package
    grok_package(sub_module_info, grokker, **kw)
  File "/home/sti-dev/plone4/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 208, in grok_package
    grok_package(sub_module_info, grokker, **kw)
  File "/home/sti-dev/plone4/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 206, in grok_package
    grok_module(module_info, grokker, **kw)
  File "/home/sti-dev/plone4/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 211, in grok_module
    grokker.grok(module_info.dotted_name, module_info.getModule(),
  File "/home/sti-dev/plone4/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/scan.py", line 141, in getModule
    self._module = resolve(self.dotted_name)
  File "/home/sti-dev/plone4/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/scan.py", line 217, in resolve
    __import__(used)
  File "/home/sti-dev/plone4/buildout-cache/eggs/brasil.gov.paginadestaque-1.0b1-py2.7.egg/brasil/gov/paginadestaque/browser/views/overrides.py", line 5, in <module>
    from collective.cover.browser.cover import View as CoverBaseView
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/sti-dev/plone4/zeocluster/parts/client1/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/sti-dev/plone4/buildout-cache/eggs/Products.CMFPlone-4.3.3-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/home/sti-dev/plone4/buildout-cache/eggs/brasil.gov.paginadestaque-1.0b1-py2.7.egg/brasil/gov/paginadestaque/configure.zcml", line 16.2-16.32
    ZopeXMLConfigurationError: File "/home/sti-dev/plone4/buildout-cache/eggs/brasil.gov.paginadestaque-1.0b1-py2.7.egg/brasil/gov/paginadestaque/browser/configure.zcml", line 12.2-12.27
    ImportError: No module named cover

**Comment by idgserpro** [comment]
@luamleiverton qual a versão do IDG você está utilizando?

**Comment by luamleiverton** [comment]
idg? desculpe a ignorância amigo..=D é que sou novo com plone.. onde posso conseguir esta informação?

**Comment by idgserpro** [comment]
@luamleiverton como você está montando o seu ambiente? Você seguiu a documentação?

https://github.com/plonegovbr/portal.buildout/blob/master/docs/producao.rst

**Comment by luamleiverton** [comment]
Sim.. mas na verdade foi um conjunto de documentos, extraí informações de manuais da secom, fóruns da interlegis, manuais da simples consultoria, entre outros.. Primeiro realizei a instalação do plone 4.3 em ambiente ubuntu, instalando-o como zeo.. posteriormente adicionei os produtos para ter acesso ao modelo de identidade visual do governo, de modo a reusar suas barras e algumas funcionalidade úteis, como as que se referem à acessibilidade.. Para tal tive que substituir o version.cfg, substituindo-o pela versão disponível em http://downloads.plone.org.br/release/1.0.3/versions.cfg.. De acordo com a definição neste arquivo o Portal padrão é o 1.0.3.. 

Só agora entendi que IDG é identidade digital de governo.. =D lamento a confusão.. 


De: "idgserpro" <notifications@github.com> 
Para: "plonegovbr/brasil.gov.paginadestaque" <brasil.gov.paginadestaque@noreply.github.com> 
Cc: "Luam leiverton Pereira dos Santos" <luam.santos@univasf.edu.br> 
Enviadas: Terça-feira, 16 de fevereiro de 2016 17:14:56 
Assunto: Re: [brasil.gov.paginadestaque] Compatibilidade do collective.cover 1.0a6 com o brasil.gov.paginadestaque 1.0 (#7) 



@luamleiverton como você está montando o seu ambiente? Você seguiu a documentação? 

https://github.com/plonegovbr/portal.buildout/blob/master/docs/producao.rst 

— 
Reply to this email directly or view it on GitHub . 


-- 
Luam Leiverton Pereira dos Santos 
Analista de Tecnologia da Informação 
Bacharel em Sistemas de Informação/Mestrando em Modelagem Computacional do Conhecimento 
Departamento de Sistemas de Informação/Secretaria de Sistemas de Informação 
www.sti.univasf.edu.br 
Universidade Federal do Vale do São Francisco-UNIVASF

**Comment by idgserpro** [comment]
@luamleiverton no seu caso, você tem duas opções:

- Atualizar o seu portal para a versão mais nova do IDG, que hoje é a 1.1.3, alterando o seu versions.cfg da versão 1.0.3 para o [versions.cfg da versão 1.1.3.1](http://downloads.plone.org.br/release/1.1.3.1/versions.cfg). Lembrando que você deve executar os upgrade steps que irão aparecer.
- Utilizar a versão [1.0a2](https://pypi.python.org/pypi/brasil.gov.paginadestaque/1.0a2) do brasil.gov.paginadestaque, pinando essa versão do seu versions.cfg da versão 1.0.3.

A segunda opção é menos arriscada, mas o ideal é você atualizar o seu portal.

De qualquer forma, ainda temos que corrigir esse problema de incompatibilidade.

**Comment by idgserpro** [comment]
Prezados (as),

Já lançamos o release 1.1.4 do IDG, com diversas correções, e esse problema não ocorre mais. Acreditamos não fazer sentido mexer na versão tão antiga quanto a 1.0.3: um volume considerável de trabalho foi feito para utilizarmos versão mais nova do collective.cover (estamos na [1.1b1 pra se ter uma idéia](https://github.com/plonegovbr/portalpadrao.release/blob/2b5d7d11089ad4a6096b7cec248d46a80d9b2b9b/1.1.4/versions.cfg#L513)): veja só o volume de alterações que [temos do collective.cover 1.0a6 para 1.1b1](https://github.com/collective/collective.cover/blob/ce4d6115185eaf38f428f5ae878599ce5fc7692c/HISTORY.rst).

Assim, fecharemos esse relato. Recomendamos a utilização da última versão do IDG.
